---
title: "Feature Engineering"
author: "Luis Tujab 1103920"
date: "2023-10-12"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(dplyr)
library(ggplot2)
```
```{r}
data <- read.csv("train_HP.CSV")
t(data)
```

#Paso 1 -tratamiento de datos faltantes

```{r}
    #Determinar que columnas tienen datos faltantes 
    colNA <- colnames(data)[!complete.cases(t(data))]
    # 1.2 substraer las columnas con datos faltanes
    IncompleteData <- data %>% select(colNA)
    
    #1.3 calcular porcentaje de datos faltantes apply(datos faltantes, 1 fila o 2 columan,  funcion )
    
    PorcentajeNA <- as.data.frame(apply(IncompleteData,2,function(col) sum(is.na(col))/ length(col) )) 
    colnames(PorcentajeNA) <- c("Porcentaje")
    PorcentajeNA
    
    #Determinar columnas que si son procesables (las que cumplen con valores abajo del 5%)
    
    colPros <- PorcentajeNA %>% 
                    filter(PorcentajeNA <= 0.06)
    colPros
```
```{r}
#1.5 Realizar imputacion de datos faltantes 
  data2 <- data 
  data2$LotFrontage_Media <- ifelse(is.na(data2$LotFrontage), mean(data$LotFrontage,na.rm = T),
                                                              data2$LotFrontage)
  data2$LotFrontage_mediana <- ifelse(is.na(data2$LotFrontage), median(data2$LotFrontage,na.rm = T), no =  data2$LotFrontage)
  
  data2
  
```


```{r}
#1.6 Distribucion de la columna lotFrintage, lotFrontage_media, loteFrontage_mediana  
data2 %>%
        ggplot(aes(x= LotFrontage,Y=..density..)) + 
          geom_density(color = "green", alpha=0.8) + 
          geom_density(aes(x=LotFrontage_Media, y=..density..),color="blue", alpha=.6)+
          geom_density(aes(x=LotFrontage_mediana, y=..density..), color="red", alpha=.6)+
            theme_minimal()
```
```{r}
#1.7 Eliminar datos faltantes 
data1<- data
nrow(data1) #
data1 <- data1[!is.na(data$LotFrontage),]
nrow(data1)
#1.8 Eliminar columnas no procesables por tener alto % 
dim(data1)

data1 <- data1[,-which(colMeans(is.na(data1))>=0.06)] 
dim(data1)


```
```{r}
#Encoding 
data1 <- data
table(data1$HouseStyle)
#2.1 Label o ordinal encoding
encode_ordinal <- function(x,order=unique(x)){
  
  x<-as.numeric(factor(x,levels = order,exclude = NULL))
  
}

data1$HouseStyle <- encode_ordinal(data1$FireplacesQu)
data1
```
```{r}
#2.2 One Hot encoding 
library(vtreat)
table(data1$BsmtQual)
pruebaOHC <- designTreatmentsZ(data1,c("BsmtQual"))
new_df <- prepare(pruebaOHC,data1,extracols = "target")
head(new_df)
```
```{r}
devtools::install_github("UBC-MDS/encodeR", force= TRUE) 

```
```{r}
library(encodeR)

ds <- frequency_encoder(data1,cat_columns = c("MSZoning", "LotShape"))
ds
```
```{r}
# 3 Feature scaling 
library(MASS)
datatemp <- Boston
summary(datatemp)
```
```{r}
datatemp %>%
    ggplot(aes(x=nox, y=..density..))+ 
        geom_density(col="green") + 
        geom_density(aes(x=age, y=..density..), col="red") + 
        geom_density(aes(x=dis, y=..density..), col="purple") + 
  theme_minimal()

```
```{r}
#3.1 Estandarizacion 

  datatemp$nox <- (datatemp$nox - mean(datatemp$nox)) / sd(datatemp$nox)
  datatemp$age <- (datatemp$age - mean(datatemp$age)) / sd(datatemp$age)
  datatemp$dis <- (datatemp$dis - mean(datatemp$dis)) / sd(datatemp$dis)
  
  datatemp %>%
  select(c("nox", "age", "dis"))
```

```{r}
##Librerias 
library(dplyr)
library(ggplot2)
library(car)
```
```{r}
#Transformaciones 

data1 %>%
  ggplot(aes(x=GrLivArea)) + 
  geom_histogram(color = "white", fill = "blue", alpha = 0.8)
theme_minimal()
```

```{r}
qqPlot(data1$GrLivArea)
```
```{r}
#Transformacion inversa 
data1$GrLivArea_inv <- (1/ data1$GrLivArea)
qqnorm(data1$GrLivArea_inv, pch=1,frame=FALSE)
qqline(data1$GrLivArea_inv, col="red", lwd=2)
```
```{r}
#Transformacion al cuadrado
data1$GrLivArea_inv <- (data1$GrLivArea^2)
qqnorm(data1$GrLivArea_inv, pch=1,frame=FALSE)
qqline(data1$GrLivArea_inv, col="red", lwd=2)
```
```{r}
#Logaritmica
data1$GrLivArea_log <- log(data1$GrLivArea)
qqnorm(data1$GrLivArea_log, pch=1,frame=FALSE)
qqline(data1$GrLivArea_log, col="red", lwd=2)
```
```{r}
#Histograma logaritmico 
data1 %>%
  ggplot(aes(x=GrLivArea_log)) + 
  geom_histogram(color = "white", fill = "green", alpha = 0.8)
theme_classic()
```
```{r}
#Outliers
dat<- ggplot2::mpg
summary(dat)
```
```{r}
min(dat$hwy)
max(dat$hwy)
range(dat$hwy)
```
```{r}
dat %>%
  ggplot(aes(hwy)) + 
  geom_histogram(color = "red", fill = "blue") + 
  theme_dark()
```

```{r}
boxplot(dat$hwy, ylab="hwy")
```
```{r}
boxplot.stats(dat$hwy)$out

```
```{r}
out<-boxplot.stats(dat$hwy)$out
out_ind <- which(dat$hwy %in% c(out))
out_ind
dat[out_ind,]
```
```{r}
lower_bound <- quantile(dat$hwy,0.01)
lower_bound
upper_bound <- quantile(dat$hwy,0.99)
upper_bound
```
```{r}
outlier_ind <- which(dat$hwy < lower_bound | dat$hwy > upper_bound)
dat[outlier_ind,]
```

